# Generated by Django 2.0 on 2018-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180704_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='writer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
