# Generated by Django 2.0 on 2018-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile_writer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='writer_name',
            field=models.CharField(default='to be added', max_length=100),
        ),
    ]
