# Generated by Django 2.0 on 2018-08-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_comment_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_image',
        ),
    ]
