# Generated by Django 2.0 on 2018-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_comment_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
