# Generated by Django 2.0 on 2018-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_comment_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
