# Generated by Django 2.0 on 2018-08-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20180821_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
