# Generated by Django 2.0 on 2018-08-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20180821_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'permissions': (('can_create_posts', 'can_change_post'),)},
        ),
    ]
