# Generated by Django 2.0 on 2018-08-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180827_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'permissions': (('can_create_posts', 'can_manipulate_post'),)},
        ),
    ]
