# Generated by Django 2.0 on 2018-08-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
