# Generated by Django 2.0 on 2018-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20180828_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text='Give a name that attracts', max_length=50, unique=True),
        ),
    ]
